/**
 * Inference & Model Strategy — Internal Types
 *
 * Re-exports shared types from types.ts and defines internal constants
 * for the inference routing subsystem.
 */

export type {
  SurvivalTier,
  ModelProvider,
  InferenceTaskType,
  ModelEntry,
  ModelPreference,
  RoutingMatrix,
  InferenceRequest,
  InferenceResult,
  InferenceCostRow,
  ModelRegistryRow,
  ModelStrategyConfig,
  ChatMessage,
} from "../types.js";

import type {
  RoutingMatrix,
  ModelEntry,
  ModelStrategyConfig,
} from "../types.js";

// === Default Retry Policy ===

export const DEFAULT_RETRY_POLICY = {
  maxRetries: 3,
  baseDelayMs: 1000,
  maxDelayMs: 30000,
} as const;

// === Per-Task Timeout Overrides (ms) ===

export const TASK_TIMEOUTS: Record<string, number> = {
  heartbeat_triage: 15_000,
  safety_check: 30_000,
  summarization: 60_000,
  agent_turn: 120_000,
  planning: 120_000,
};

// === Static Model Baseline ===
// Known models with realistic pricing (hundredths of cents per 1k tokens)

export const STATIC_MODEL_BASELINE: Omit<ModelEntry, "lastSeen" | "createdAt" | "updatedAt">[] = [
  // Google Models
  {
    modelId: "gemma-4-31b-it",
    provider: "google",
    displayName: "Gemma 4 31B IT",
    tierMinimum: "normal",
    costPer1kInput: 1,
    costPer1kOutput: 2,
    maxTokens: 8192,
    contextWindow: 131072,
    supportsTools: true,
    supportsVision: false,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "gemma-4-26b-a4b-it",
    provider: "google",
    displayName: "Gemma 4 26B IT",
    tierMinimum: "low_compute",
    costPer1kInput: 1,
    costPer1kOutput: 2,
    maxTokens: 8192,
    contextWindow: 131072,
    supportsTools: true,
    supportsVision: false,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "gemini-2.5-flash",
    provider: "google",
    displayName: "Gemini 2.5 Flash",
    tierMinimum: "normal",
    costPer1kInput: 1,
    costPer1kOutput: 4,
    maxTokens: 8192,
    contextWindow: 1048576,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "gemini-2.5-pro",
    provider: "google",
    displayName: "Gemini 2.5 Pro",
    tierMinimum: "normal",
    costPer1kInput: 12,
    costPer1kOutput: 50,
    maxTokens: 8192,
    contextWindow: 1048576,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "gemini-3.1-flash-lite",
    provider: "google",
    displayName: "Gemini 3.1 Flash Lite",
    tierMinimum: "low_compute",
    costPer1kInput: 1,
    costPer1kOutput: 4,
    maxTokens: 8192,
    contextWindow: 1048576,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "gemini-3.6-flash",
    provider: "google",
    displayName: "Gemini 3.6 Flash",
    tierMinimum: "normal",
    costPer1kInput: 1,
    costPer1kOutput: 4,
    maxTokens: 8192,
    contextWindow: 1048576,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },

  // Anthropic Claude Models
  {
    modelId: "claude-3-5-sonnet-20241022",
    provider: "anthropic",
    displayName: "Claude 3.5 Sonnet",
    tierMinimum: "normal",
    costPer1kInput: 30,
    costPer1kOutput: 150,
    maxTokens: 8192,
    contextWindow: 200000,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "claude-3-5-haiku-20241022",
    provider: "anthropic",
    displayName: "Claude 3.5 Haiku",
    tierMinimum: "low_compute",
    costPer1kInput: 8,
    costPer1kOutput: 40,
    maxTokens: 8192,
    contextWindow: 200000,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "claude-3-opus-20240229",
    provider: "anthropic",
    displayName: "Claude 3 Opus",
    tierMinimum: "normal",
    costPer1kInput: 150,
    costPer1kOutput: 750,
    maxTokens: 4096,
    contextWindow: 200000,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },

  // xAI Grok Models
  {
    modelId: "grok-2-latest",
    provider: "xai",
    displayName: "Grok 2 Latest",
    tierMinimum: "normal",
    costPer1kInput: 20,
    costPer1kOutput: 100,
    maxTokens: 8192,
    contextWindow: 131072,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "grok-beta",
    provider: "xai",
    displayName: "Grok Beta",
    tierMinimum: "low_compute",
    costPer1kInput: 10,
    costPer1kOutput: 50,
    maxTokens: 8192,
    contextWindow: 131072,
    supportsTools: true,
    supportsVision: false,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  // OpenAI Models
  {
    modelId: "gpt-4o",
    provider: "openai",
    displayName: "GPT-4o",
    tierMinimum: "normal",
    costPer1kInput: 50,
    costPer1kOutput: 150,
    maxTokens: 16384,
    contextWindow: 128000,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "gpt-4o-mini",
    provider: "openai",
    displayName: "GPT-4o Mini",
    tierMinimum: "low_compute",
    costPer1kInput: 1,
    costPer1kOutput: 6,
    maxTokens: 16384,
    contextWindow: 128000,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "anthropic/claude-3.5-sonnet:beta",
    provider: "openrouter",
    displayName: "OR Claude 3.5 Sonnet",
    tierMinimum: "normal",
    costPer1kInput: 30,
    costPer1kOutput: 150,
    maxTokens: 8192,
    contextWindow: 200000,
    supportsTools: true,
    supportsVision: true,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "meta/llama3-70b-instruct",
    provider: "openrouter",
    displayName: "OR Llama 3 70B",
    tierMinimum: "low_compute",
    costPer1kInput: 5,
    costPer1kOutput: 5,
    maxTokens: 8192,
    contextWindow: 131000,
    supportsTools: true,
    supportsVision: false,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "meta/llama3-8b-instruct",
    provider: "openrouter",
    displayName: "OR Llama 3 8B",
    tierMinimum: "critical",
    costPer1kInput: 0,
    costPer1kOutput: 0,
    maxTokens: 8192,
    contextWindow: 131000,
    supportsTools: true,
    supportsVision: false,
    parameterStyle: "max_tokens",
    enabled: true,
  },
  {
    modelId: "nvidia/nemotron-3-super-120b-a12b",
    provider: "nvidia",
    displayName: "NVIDIA Nemotron 3",
    tierMinimum: "normal",
    costPer1kInput: 10,
    costPer1kOutput: 20,
    maxTokens: 8192,
    contextWindow: 131000,
    supportsTools: true,
    supportsVision: false,
    parameterStyle: "max_tokens",
    enabled: true,
  },
];

// === Default Routing Matrix ===
// Maps (tier, taskType) -> ModelPreference with candidate models

export const DEFAULT_ROUTING_MATRIX: RoutingMatrix = {
  high: {
    agent_turn: { candidates: ["gemini-2.5-flash", "anthropic/claude-3.5-sonnet:beta", "claude-3-5-sonnet-20241022", "nvidia/nemotron-3-super-120b-a12b", "meta/llama3-70b-instruct", "gpt-4o", "gemini-3.1-flash-lite"], maxTokens: 8192, ceilingCents: -1 },
    heartbeat_triage: { candidates: ["gemini-3.1-flash-lite", "meta/llama3-8b-instruct", "gpt-4o-mini", "claude-3-5-haiku-20241022", "gemini-2.5-flash"], maxTokens: 2048, ceilingCents: 5 },
    safety_check: { candidates: ["gemini-2.5-flash", "claude-3-5-haiku-20241022", "gpt-4o-mini", "gemini-3.1-flash-lite"], maxTokens: 4096, ceilingCents: 20 },
    summarization: { candidates: ["gemini-2.5-flash", "claude-3-5-haiku-20241022", "gpt-4o-mini", "meta/llama3-8b-instruct", "gemini-3.1-flash-lite"], maxTokens: 4096, ceilingCents: 15 },
    planning: { candidates: ["gemini-2.5-pro", "anthropic/claude-3.5-sonnet:beta", "claude-3-5-sonnet-20241022", "nvidia/nemotron-3-super-120b-a12b", "gpt-4o", "gemini-2.5-flash"], maxTokens: 8192, ceilingCents: -1 },
  },
  normal: {
    agent_turn: { candidates: ["gemini-2.5-flash", "anthropic/claude-3.5-sonnet:beta", "claude-3-5-sonnet-20241022", "nvidia/nemotron-3-super-120b-a12b", "meta/llama3-70b-instruct", "gpt-4o-mini", "gemini-3.1-flash-lite"], maxTokens: 4096, ceilingCents: -1 },
    heartbeat_triage: { candidates: ["gemini-3.1-flash-lite", "meta/llama3-8b-instruct", "gpt-4o-mini", "claude-3-5-haiku-20241022", "gemini-2.5-flash"], maxTokens: 1024, ceilingCents: 5 },
    safety_check: { candidates: ["gemini-3.1-flash-lite", "claude-3-5-haiku-20241022", "gpt-4o-mini", "gemini-2.5-flash"], maxTokens: 2048, ceilingCents: 10 },
    summarization: { candidates: ["gemini-3.1-flash-lite", "claude-3-5-haiku-20241022", "gpt-4o-mini", "gemini-2.5-flash"], maxTokens: 2048, ceilingCents: 5 },
    planning: { candidates: ["gemini-2.5-flash", "anthropic/claude-3.5-sonnet:beta", "claude-3-5-sonnet-20241022", "nvidia/nemotron-3-super-120b-a12b", "gemini-3.1-flash-lite"], maxTokens: 4096, ceilingCents: -1 },
  },
  low_compute: {
    agent_turn: { candidates: ["gemini-3.1-flash-lite", "meta/llama3-8b-instruct", "gpt-4o-mini", "claude-3-5-haiku-20241022", "gemini-2.5-flash"], maxTokens: 2048, ceilingCents: -1 },
    heartbeat_triage: { candidates: ["gemini-3.1-flash-lite", "meta/llama3-8b-instruct", "gpt-4o-mini"], maxTokens: 512, ceilingCents: 0 },
    safety_check: { candidates: ["gemini-3.1-flash-lite", "meta/llama3-8b-instruct", "gpt-4o-mini"], maxTokens: 1024, ceilingCents: 0 },
    summarization: { candidates: ["gemini-3.1-flash-lite", "meta/llama3-8b-instruct", "gpt-4o-mini"], maxTokens: 1024, ceilingCents: 0 },
    planning: { candidates: ["gemini-3.1-flash-lite", "meta/llama3-8b-instruct", "gpt-4o-mini", "claude-3-5-haiku-20241022"], maxTokens: 2048, ceilingCents: -1 },
  },
  critical: {
    agent_turn: { candidates: ["gemini-3.1-flash-lite", "meta/llama3-8b-instruct", "gpt-4o-mini", "claude-3-5-haiku-20241022"], maxTokens: 1024, ceilingCents: -1 },
    heartbeat_triage: { candidates: ["gemini-3.1-flash-lite", "gpt-4o-mini"], maxTokens: 256, ceilingCents: 0 },
    safety_check: { candidates: ["gemini-3.1-flash-lite", "gpt-4o-mini"], maxTokens: 512, ceilingCents: 0 },
    summarization: { candidates: ["gemini-3.1-flash-lite", "gpt-4o-mini"], maxTokens: 512, ceilingCents: 0 },
    planning: { candidates: ["gemini-3.1-flash-lite", "gpt-4o-mini"], maxTokens: 1024, ceilingCents: -1 },
  },
  dead: {
    agent_turn: { candidates: [], maxTokens: 0, ceilingCents: 0 },
    heartbeat_triage: { candidates: [], maxTokens: 0, ceilingCents: 0 },
    safety_check: { candidates: [], maxTokens: 0, ceilingCents: 0 },
    summarization: { candidates: [], maxTokens: 0, ceilingCents: 0 },
    planning: { candidates: [], maxTokens: 0, ceilingCents: 0 },
  },
};

// === Default Model Strategy Config ===

export const DEFAULT_MODEL_STRATEGY_CONFIG: ModelStrategyConfig = {
  inferenceModel: "gemma-4-31b-it",
  lowComputeModel: "gemma-4-26b-a4b-it",
  criticalModel: "gemma-4-26b-a4b-it",
  maxTokensPerTurn: 8192,
  hourlyBudgetCents: 0,
  sessionBudgetCents: 0,
  perCallCeilingCents: 0,
  enableModelFallback: true,
  anthropicApiVersion: "2023-06-01",
};
